<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-03-26 12:28

$extensionPath = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('t3startup');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'TYPO3\CMS\T3Startup\Hooks\TypoScriptTemplate' => $extensionClassesPath . 'Hooks/TypoScriptTemplate.php',
	'TYPO3\CMS\T3Startup\Utility\Configuration' => $extensionClassesPath . 'Utility/Configuration.php',
	'TYPO3\CMS\T3Startup\Utility\Context' => $extensionClassesPath . 'Utility/Context.php'
);
?>